### ISSUE TITLE
elisp-slime-nav-find-elisp-thing-at-point Causes error

### ISSUE THREAD

**Issue by michael-angelozzi** [purcell/elisp-slime-nav#20]
Using Emacs 26.3, Ubuntu 18.04:

If I position point over `setq` and run `elisp-slime-nav-find-elisp-thing-at-point` I get the following error:

    find-library-name: Can’t find library /usr/share/emacs/26.3/lisp/subr.el

Also the Hotkey `M-` runs `xref-find-definitions` for me.

`init.el` setup (Using MELPA): 
```
(use-package elisp-slime-nav
  :ensure t
  :commands (elisp-slime-nav-mode
             elisp-slime-nav-find-elisp-thing-at-point)
  :config
  (dolist (hook '(emacs-lisp-mode-hook ielm-mode-hook))
    (add-hook hook 'elisp-slime-nav-mode))
  )

```

**Comment by purcell** [comment]
> If I position point over `setq` and run `elisp-slime-nav-find-elisp-thing-at-point` I get the following error:
> 
> ```
> find-library-name: Can’t find library /usr/share/emacs/26.3/lisp/subr.el
> ```

I have the same Emacs version and the source for this function is also not available. That's not the fault of this package though! :-)


> Also the Hotkey `M-` runs `xref-find-definitions` for me.

I think the key you're referring to there was truncated. But yes, if you have a very recent Emacs then you might prefer to use xref instead of this package. I don't consider it a bug that the bindings are the same: it's intentional, since `M-.` and `M-,` were the standard bindings for this behaviour before `xref` was added to Emacs, and that's also why those bindings were used in `xref`.
